In [1]:
import pandas as pd
import numpy as np

In [2]:
import json

with open("../preprocessed data/city_graph.json", "r") as f:
    df_city = json.load(f)

In [3]:
device = pd.read_csv("../preprocessed data/device_locations.csv")

In [4]:
device.head()

   user_id  location_id            timestamp
0        0          551  2008-10-23 02:53:04
1        0          551  2008-10-23 02:53:10
2        0          551  2008-10-23 02:53:15
3        0          551  2008-10-23 02:53:20
4        0          551  2008-10-23 02:53:25

In [5]:
device["timestamp"].nunique()

13246478

In [6]:
device["user_id"].nunique()

179

In [7]:
device["location_id"].nunique()

883

In [8]:
len(df_city["nodes"])

900

In [9]:
node_ids = [n["id"] for n in df_city["nodes"]]
len(set(node_ids))

900

In [10]:
x_vals = [n["x"] for n in df_city["nodes"]]
y_vals = [n["y"] for n in df_city["nodes"]]

len(set(x_vals))
len(set(y_vals))

30

In [11]:
df_nodes = pd.DataFrame(df_city["nodes"])
df_nodes.head()

  id        x       y
0  0  116.205  39.805
1  1  116.215  39.805
2  2  116.225  39.805
3  3  116.235  39.805
4  4  116.245  39.805

In [12]:
device_locations = set(device["location_id"].astype(str))
city_node_ids = set(df_nodes["id"].astype(str))

In [13]:
missing_in_city = device_locations - city_node_ids
len(missing_in_city)

0

In [14]:
unused_city_nodes = city_node_ids - device_locations
len(unused_city_nodes)

17